name = "hs-code-verifier-api"
compatibility_date = "2024-01-01"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]

account_id = ""  # AUTOMATYCZNIE Z GITHUB SECRETS
workers_dev = true

[vars]
ENVIRONMENT = "production"
VERSION = "1.4.3"
MAX_REQUESTS_PER_DAY = 20000
ALLOWED_ORIGINS = "https://hs-code-ver.pages.dev"

[[kv_namespaces]]
binding = "HS_DATABASE"
id = "d4e909bdc6114613ab76635fadb855b2"

[[kv_namespaces]]
binding = "SESSIONS"
id = "0d2f1b8c65434fe5b1e04407a5777852"

[[kv_namespaces]]
binding = "LOGS"
id = "da60a876321c4026b10053c05ef0a59f"

[[kv_namespaces]]
binding = "USERS"
id = "848ff6df2cb84046b48f1d64151f1cb7"

[triggers]
crons = ["0 3 * * *"]